// This file will be auto-generated by: supabase gen types typescript
// For now, define key types manually based on the SQL schema

export type Database = {
  public: {
    Tables: {
      regions: {
        Row: {
          id: string;
          slug: string;
          name_en: string;
          name_zh: string | null;
          type: 'country' | 'state' | 'county' | 'city' | 'neighborhood' | 'borough';
          parent_id: string | null;
          timezone: string;
          latitude: number | null;
          longitude: number | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['regions']['Row'], 'id' | 'created_at'> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['regions']['Insert']>;
      };
      profiles: {
        Row: {
          id: string;
          username: string | null;
          display_name: string;
          avatar_url: string | null;
          cover_image_url: string | null;
          bio: string | null;
          bio_zh: string | null;
          bio_en: string | null;
          location_text: string | null;
          region_id: string | null;
          profile_type: 'user' | 'creator' | 'expert' | 'professional' | 'community_leader' | 'business_owner';
          headline: string | null;
          primary_language: 'zh' | 'en' | 'bilingual';
          is_verified: boolean;
          is_featured: boolean;
          follower_count: number;
          following_count: number;
          post_count: number;
          blog_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at' | 'follower_count' | 'following_count' | 'post_count' | 'blog_count'>;
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      articles: {
        Row: {
          id: string;
          slug: string;
          content_vertical: string;
          category_id: string | null;
          region_id: string | null;
          title_en: string | null;
          title_zh: string | null;
          summary_en: string | null;
          summary_zh: string | null;
          body_en: string | null;
          body_zh: string | null;
          cover_image_url: string | null;
          author_id: string | null;
          source_name: string | null;
          source_url: string | null;
          source_type: string | null;
          editorial_status: 'draft' | 'ai_drafted' | 'human_reviewed' | 'published' | 'archived';
          trust_score: number;
          ai_summary_en: string | null;
          ai_summary_zh: string | null;
          ai_key_facts: Record<string, unknown> | null;
          ai_faq: Array<{ q: string; a: string }> | null;
          ai_tags: string[] | null;
          published_at: string | null;
          view_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['articles']['Row']> & {
          slug: string;
          content_vertical: string;
        };
        Update: Partial<Database['public']['Tables']['articles']['Insert']>;
      };
      businesses: {
        Row: {
          id: string;
          slug: string;
          display_name: string;
          display_name_zh: string | null;
          short_desc_en: string | null;
          short_desc_zh: string | null;
          full_desc_en: string | null;
          full_desc_zh: string | null;
          phone: string | null;
          email: string | null;
          website_url: string | null;
          wechat_id: string | null;
          status: 'pending' | 'active' | 'suspended' | 'claimed' | 'unclaimed';
          verification_status: 'unverified' | 'pending' | 'verified';
          claimed_by_user_id: string | null;
          current_plan: string;
          ai_summary_en: string | null;
          ai_summary_zh: string | null;
          ai_faq: Array<{ q: string; a: string }> | null;
          ai_tags: string[] | null;
          review_count: number;
          avg_rating: number | null;
          view_count: number;
          lead_count: number;
          is_featured: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['businesses']['Row']> & {
          slug: string;
          display_name: string;
        };
        Update: Partial<Database['public']['Tables']['businesses']['Insert']>;
      };
      forum_threads: {
        Row: {
          id: string;
          slug: string;
          title: string;
          body: string;
          board_id: string;
          author_id: string;
          region_id: string | null;
          language: 'zh' | 'en' | 'bilingual';
          status: string;
          is_pinned: boolean;
          is_featured: boolean;
          view_count: number;
          reply_count: number;
          vote_count: number;
          last_replied_at: string;
          ai_summary_zh: string | null;
          ai_summary_en: string | null;
          ai_tags: string[] | null;
          ai_intent: string | null;
          ai_merchant_ids: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['forum_threads']['Row']> & {
          slug: string;
          title: string;
          body: string;
          board_id: string;
          author_id: string;
        };
        Update: Partial<Database['public']['Tables']['forum_threads']['Insert']>;
      };
      voice_posts: {
        Row: {
          id: string;
          author_id: string;
          post_type: 'short_post' | 'blog' | 'guide_post' | 'recommendation' | 'question' | 'event_post' | 'opinion' | 'note' | 'video';
          title: string | null;
          slug: string | null;
          excerpt: string | null;
          content: string;
          cover_image_url: string | null;
          video_url: string | null;
          video_thumbnail_url: string | null;
          video_duration_seconds: number | null;
          aspect_ratio: string;
          cover_images: string[] | null;
          location_text: string | null;
          visibility: 'public' | 'followers_only' | 'private';
          status: string;
          region_id: string | null;
          language: 'zh' | 'en' | 'bilingual';
          topic_tags: string[] | null;
          like_count: number;
          comment_count: number;
          save_count: number;
          share_count: number;
          view_count: number;
          published_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['voice_posts']['Row']> & {
          author_id: string;
          content: string;
        };
        Update: Partial<Database['public']['Tables']['voice_posts']['Insert']>;
      };
      discover_topics: {
        Row: {
          id: string;
          slug: string;
          name_zh: string;
          name_en: string | null;
          description: string | null;
          icon_emoji: string | null;
          cover_image_url: string | null;
          post_count: number;
          follower_count: number;
          is_trending: boolean;
          is_featured: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['discover_topics']['Row']> & {
          slug: string;
          name_zh: string;
        };
        Update: Partial<Database['public']['Tables']['discover_topics']['Insert']>;
      };
      discover_post_topics: {
        Row: {
          id: string;
          post_id: string;
          topic_id: string;
        };
        Insert: {
          post_id: string;
          topic_id: string;
        };
        Update: Partial<Database['public']['Tables']['discover_post_topics']['Insert']>;
      };
      discover_post_businesses: {
        Row: {
          id: string;
          post_id: string;
          business_id: string;
          relation_note: string | null;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          post_id: string;
          business_id: string;
          relation_note?: string;
          sort_order?: number;
        };
        Update: Partial<Database['public']['Tables']['discover_post_businesses']['Insert']>;
      };
      leads: {
        Row: {
          id: string;
          business_id: string | null;
          source_type: string;
          user_id: string | null;
          contact_name: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          contact_wechat: string | null;
          message: string | null;
          preferred_contact: string;
          ai_intent_score: number | null;
          ai_summary: string | null;
          ai_urgency: string;
          status: 'new' | 'contacted' | 'qualified' | 'converted' | 'closed';
          region_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['leads']['Row']> & {
          source_type: string;
        };
        Update: Partial<Database['public']['Tables']['leads']['Insert']>;
      };
    };
    Views: {
      v_published_articles: {
        Row: Database['public']['Tables']['articles']['Row'] & {
          region_name_en: string | null;
          region_name_zh: string | null;
          category_name_en: string | null;
          category_name_zh: string | null;
        };
      };
    };
  };
};
